Repository Programmers-3th-Team-Kim/study-room-BE, pull requests merged in 2024-09, with the labels that each got.

#12 [FEAT] 로그인, 회원가입 구현
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/jwt.strategy.ts
  src/main.ts
  src/users/dto/createUser.dto.ts
  src/users/users.module.ts
  src/users/users.schema.ts
  src/users/users.service.ts
Labels: 📬 API

#10 [FEAT] 공부방 조회, 검색 API 구현
  src/app.module.ts
  src/main.ts
  src/rooms/dto/createRoom.dto.ts
  src/rooms/dto/showRoom.dto.ts
  src/rooms/rooms.controller.ts
  src/rooms/rooms.module.ts
  src/rooms/rooms.schema.ts
  src/rooms/rooms.service.ts
  src/schemas/chats.schema.ts
Labels: 📬 API

#16 [FEAT] 공부방 생성
  src/rooms/dto/createRoom.dto.ts
  src/rooms/dto/requestRoom.dto.ts
  src/rooms/dto/responseRoom.dto.ts
  src/rooms/dto/showRoom.dto.ts
  src/rooms/rooms.controller.ts
  src/rooms/rooms.schema.ts
  src/rooms/rooms.service.ts
Labels: 📬 API

#24 [REFACTOR] 로그인 개선
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/jwt-auth.guard.ts
  src/main.ts
  src/users/dto/createUser.dto.ts
Labels: 🐞 Fix, 📬 API, 🔨 Refactor

#20 [FEAT] 플래너 페이지 할 일 API 구현
  src/app.module.ts
  src/planners/dto/planner.dto.ts
  src/planners/planners.controller.ts
  src/planners/planners.module.ts
  src/planners/planners.schema.ts
  src/planners/planners.service.ts
Labels: 🐞 Fix, 📬 API, 🔨 Refactor

#28 [FIX] 공부방 조회
  src/rooms/rooms.service.ts
Labels: 🐞 Fix, 📬 API
