Repository Programmers-3th-Team-Kim/study-room-BE, pull requests merged in 2024-10, with the labels that each got.

#30 [FEAT] 회원 정보 관련 API 구현
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/changePassword.dto.ts
  src/auth/dto/refreshToken.dto.ts
  src/auth/jwt-auth.guard.ts
  src/users/dto/updateUserProfile.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: 🐞 Fix, 📬 API, 🔨 Refactor

#32 [FIX] 플래너 페이지 할 일 create, update API 버그 수정 - 동작 방식 변경
  src/planners/dto/planner.dto.ts
  src/planners/planners.controller.ts
  src/planners/planners.schema.ts
  src/planners/planners.service.ts
  src/socket/dto/clientToServer.dto.ts
  src/socket/dto/planner.dto.ts
  src/socket/dto/serverToClient.dto.ts
  src/socket/socket.gateway.ts
  src/socket/socket.service.ts
  src/socket/socketExceptionFilter.ts
  src/users/users.schema.ts
Labels: 🐞 Fix, 📬 API, 🔨 Refactor

#41 [FIX] samsite 설정 문제 해결
  src/auth/auth.service.ts
  src/users/users.schema.ts
Labels: 🐞 Fix

#43 [CHORE] 도커 파일 타임존 세팅
  Dockerfile
Labels: ⚙ Setting, 🌏 Deploy
